ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Copy the prometheus.yml configuration file to the container
COPY prometheus/prometheus.yml /etc/prometheus/prometheus.yml


# Command to run Prometheus
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.enable-remote-write-receiver"]