global:
  scrape_interval: 15s          # how often Prometheus pulls targets

scrape_configs:
  # 1. Prometheus scrapes itself
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  # 2. Scrape Alloy's public endpoint
  - job_name: alloy_public
    scheme: https               # Railway's public domains are TLS
    metrics_path: /metrics      # Alloy exposes metrics at /metrics
    static_configs:
      - targets:
          - grafana-alloy-production.up.railway.app    # no scheme, no slash
